name: Integration

on: [push]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Setup go
        uses: actions/setup-go@v1
        with:
          go-version: '1.13.x'
      - name: Download dependencies
        run: go get -t -v ./...
      - name: Vet
        run: make vet
      - name: Test
        run: make test

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Setup go
        uses: actions/setup-go@v1
        with:
          go-version: '1.13.x'
      - name: Download dependencies
        run: go get -t -v ./...
      - name: Build
        run: make build

  docker:
    name: Docker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Docker
        run: make docker
