name: Quality

on: [push]

jobs:
  golangci:
    name: GolangCI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - shell: bash
        run: |
          git submodule sync --recursive
          git submodule update --init --force --recursive --depth=1
      - name: GolangCI
        uses: Mushus/golangci-lint-action@master
        with:
          config: .golangci.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
